DELETE FROM `bank`;

INSERT INTO `bank` (`bank_code`, `name`) VALUES ('654', 'Banco A.J.Renner S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('246', 'Banco ABC Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('075', 'Banco ABN AMRO S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('121', 'Banco Agibank S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('025', 'Banco Alfa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('641', 'Banco Alvorada S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('065', 'Banco Andbank (Brasil) S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('213', 'Banco Arbi S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('096', 'Banco B3 S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('024', 'Banco BANDEPE S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('318', 'Banco BMG S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('752', 'Banco BNP Paribas Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('107', 'Banco BOCOM BBM S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('063', 'Banco Bradescard S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('036', 'Banco Bradesco BBI S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('122', 'Banco Bradesco BERJ S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('204', 'Banco Bradesco Cartões S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('394', 'Banco Bradesco Financiamentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('237', 'Banco Bradesco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('218', 'Banco BS2 S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('208', 'Banco BTG Pactual S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('473', 'Banco Caixa Geral - Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('412', 'Banco Capital S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('040', 'Banco Cargill S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('266', 'Banco Cédula S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('739', 'Banco Cetelem S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('233', 'Banco Cifra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('745', 'Banco Citibank S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('241', 'Banco Clássico S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('095', 'Banco Confidence de Câmbio S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('756', 'Banco Cooperativo do Brasil S.A. - BANCOOB');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('748', 'Banco Cooperativo Sicredi S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('222', 'Banco Credit Agricole Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('505', 'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('069', 'Banco Crefisa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('003', 'Banco da Amazônia S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('083', 'Banco da China Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('707', 'Banco Daycoval S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('300', 'Banco de La Nacion Argentina');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('495', 'Banco de La Provincia de Buenos Aires');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('494', 'Banco de La Republica Oriental del Uruguay');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('001', 'Banco do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('047', 'Banco do Estado de Sergipe S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('037', 'Banco do Estado do Pará S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('041', 'Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('004', 'Banco do Nordeste do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('265', 'Banco Fator S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('224', 'Banco Fibra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('626', 'Banco Ficsa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('094', 'Banco Finaxis S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('612', 'Banco Guanabara S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('012', 'Banco INBURSA de Investimentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('604', 'Banco Industrial do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('653', 'Banco Indusval S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('077', 'Banco Inter S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('630', 'Banco Intercap S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('249', 'Banco Investcred Unibanco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('184', 'Banco Itaú BBA S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('029', 'Banco Itaú Consignado S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('479', 'Banco ItauBank S.A');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('376', 'Banco J. P. Morgan S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('074', 'Banco J. Safra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('217', 'Banco John Deere S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('076', 'Banco KDB S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('757', 'Banco KEB HANA do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('600', 'Banco Luso Brasileiro S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('243', 'Banco Máxima S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('720', 'Banco Maxinvest S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('389', 'Banco Mercantil do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('370', 'Banco Mizuho do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('746', 'Banco Modal S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('066', 'Banco Morgan Stanley S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('456', 'Banco MUFG Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('007', 'Banco Nacional de Desenvolvimento Econômico e Social - BNDES');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('169', 'Banco Olé Bonsucesso Consignado S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('079', 'Banco Original do Agronegócio S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('212', 'Banco Original S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('712', 'Banco Ourinvest S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('623', 'Banco PAN S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('611', 'Banco Paulista S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('643', 'Banco Pine S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('658', 'Banco Porto Real de Investimentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('747', 'Banco Rabobank International Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('633', 'Banco Rendimento S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('741', 'Banco Ribeirão Preto S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('120', 'Banco Rodobens S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('422', 'Banco Safra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('033', 'Banco Santander  (Brasil)  S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('743', 'Banco Semear S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('754', 'Banco Sistema S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('366', 'Banco Société Générale Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('637', 'Banco Sofisa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('464', 'Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('082', 'Banco Topázio S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('634', 'Banco Triângulo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('018', 'Banco Tricury S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('655', 'Banco Votorantim S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('610', 'Banco VR S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('119', 'Banco Western Union do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('124', 'Banco Woori Bank do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('021', 'BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('755', 'Bank of America Merrill Lynch Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('081', 'BBN Banco Brasileiro de Negócios S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('250', 'BCV - Banco de Crédito e Varejo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('144', 'BEXS Banco de Câmbio S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('017', 'BNY Mellon Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('126', 'BR Partners Banco de Investimento S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('125', 'Brasil Plural S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('070', 'BRB - Banco de Brasília S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('092', 'Brickell S.A. Crédito, Financiamento e Investimento');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('104', 'Caixa Econômica Federal');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('114', 'Central das Cooperativas de Economia e Crédito Mútuo do Estado do Espírito Santo Ltda.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('320', 'China Construction Bank (Brasil) Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('477', 'Citibank N.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('163', 'Commerzbank Brasil S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('136', 'CONFEDERACAO NACIONAL DAS COOPERATIVAS CENTRAIS UNICREDS');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('097', 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('085', 'Cooperativa Central de Crédito Urbano-CECRED');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('090', 'Cooperativa Central de Economia e Crédito Mutuo - SICOOB UNIMAIS');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('087', 'Cooperativa Central de Economia e Crédito Mútuo das Unicreds de Santa Catarina e Paraná');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('089', 'Cooperativa de Crédito Rural da Região da Mogiana');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('098', 'CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('487', 'Deutsche Bank S.A. - Banco Alemão');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('064', 'Goldman Sachs do Brasil Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('135', 'Gradual Corretora de Câmbio,Títulos e Valores Mobiliários S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('078', 'Haitong Banco de Investimento do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('062', 'Hipercard Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('269', 'HSBC Brasil S.A. - Banco de Investimento');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('132', 'ICBC do Brasil Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('492', 'ING Bank N.V.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('139', 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('652', 'Itaú Unibanco Holding S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('341', 'Itaú Unibanco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('488', 'JPMorgan Chase Bank, National Association');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('399', 'Kirton Bank S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('128', 'MS Bank S.A. Banco de Câmbio');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('014', 'Natixis Brasil S.A. Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('753', 'Novo Banco Continental S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('613', 'Omni Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('254', 'Paraná Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('751', 'Scotiabank Brasil S.A. Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('118', 'Standard Chartered Bank (Brasil) S/A–Bco Invest.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('129', 'UBS Brasil Banco de Investimento S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('091', 'Unicred Central do Rio Grande do Sul');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('084', 'Uniprime Norte do Paraná');