INSERT INTO `bank` (`bank_code`, `name`) VALUES ('654', 'Banco A.J.Renner S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('246', 'Banco ABC Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('025', 'Banco Alfa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('641', 'Banco Alvorada S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('213', 'Banco Arbi S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('019', 'Banco Azteca do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('029', 'Banco Banerj S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('000', 'Banco Bankpar S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('740', 'Banco Barclays S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('107', 'Banco BBM S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('031', 'Banco Beg S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('739', 'Banco BGN S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('096', 'Banco BM&F de Serviços de Liquidação e Custódia S.A');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('318', 'Banco BMG S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('752', 'Banco BNP Paribas Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('248', 'Banco Boavista Interatlântico S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('218', 'Banco Bonsucesso S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('065', 'Banco Bracce S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('036', 'Banco Bradesco BBI S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('204', 'Banco Bradesco Cartões S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('394', 'Banco Bradesco Financiamentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('237', 'Banco Bradesco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('225', 'Banco Brascan S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M15', 'Banco BRJ S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('208', 'Banco BTG Pactual S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('044', 'Banco BVA S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('263', 'Banco Cacique S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('473', 'Banco Caixa Geral - Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('412', 'Banco Capital S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('040', 'Banco Cargill S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('745', 'Banco Citibank S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M08', 'Banco Citicard S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('241', 'Banco Clássico S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M19', 'Banco CNH Capital S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('215', 'Banco Comercial e de Investimento Sudameris S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('756', 'Banco Cooperativo do Brasil S.A. - BANCOOB');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('748', 'Banco Cooperativo Sicredi S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('075', 'Banco CR2 S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('721', 'Banco Credibel S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('222', 'Banco Credit Agricole Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('505', 'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('229', 'Banco Cruzeiro do Sul S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('266', 'Banco Cédula S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('003', 'Banco da Amazônia S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('083-3', 'Banco da China Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M21', 'Banco Daimlerchrysler S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('707', 'Banco Daycoval S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('300', 'Banco de La Nacion Argentina');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('495', 'Banco de La Provincia de Buenos Aires');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('494', 'Banco de La Republica Oriental del Uruguay');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M06', 'Banco de Lage Landen Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('024', 'Banco de Pernambuco S.A. - BANDEPE');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('456', 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('214', 'Banco Dibens S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('001', 'Banco do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('047', 'Banco do Estado de Sergipe S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('037', 'Banco do Estado do Pará S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('039', 'Banco do Estado do Piauí S.A. - BEP');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('041', 'Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('004', 'Banco do Nordeste do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('265', 'Banco Fator S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M03', 'Banco Fiat S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('224', 'Banco Fibra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('626', 'Banco Ficsa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M18', 'Banco Ford S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('233', 'Banco GE Capital S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('734', 'Banco Gerdau S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M07', 'Banco GMAC S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('612', 'Banco Guanabara S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M22', 'Banco Honda S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('063', 'Banco Ibi S.A. Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M11', 'Banco IBM S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('604', 'Banco Industrial do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('320', 'Banco Industrial e Comercial S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('653', 'Banco Indusval S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('630', 'Banco Intercap S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('077-9', 'Banco Intermedium S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('249', 'Banco Investcred Unibanco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M09', 'Banco Itaucred Financiamentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('184', 'Banco Itaú BBA S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('479', 'Banco ItaúBank S.A');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('376', 'Banco J. P. Morgan S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('074', 'Banco J. Safra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('217', 'Banco John Deere S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('076', 'Banco KDB S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('757', 'Banco KEB do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('600', 'Banco Luso Brasileiro S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('212', 'Banco Matone S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M12', 'Banco Maxinvest S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('389', 'Banco Mercantil do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('746', 'Banco Modal S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M10', 'Banco Moneo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('738', 'Banco Morada S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('066', 'Banco Morgan Stanley S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('243', 'Banco Máxima S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('045', 'Banco Opportunity S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M17', 'Banco Ourinvest S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('623', 'Banco Panamericano S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('611', 'Banco Paulista S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('613', 'Banco Pecúnia S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('094-2', 'Banco Petra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('643', 'Banco Pine S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('724', 'Banco Porto Seguro S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('735', 'Banco Pottencial S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('638', 'Banco Prosper S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M24', 'Banco PSA Finance Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('747', 'Banco Rabobank International Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('088-4', 'Banco Randon S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('356', 'Banco Real S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('633', 'Banco Rendimento S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('741', 'Banco Ribeirão Preto S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M16', 'Banco Rodobens S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('072', 'Banco Rural Mais S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('453', 'Banco Rural S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('422', 'Banco Safra S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('033', 'Banco Santander (Brasil) S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('250', 'Banco Schahin S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('743', 'Banco Semear S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('749', 'Banco Simples S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('366', 'Banco Société Générale Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('637', 'Banco Sofisa S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('012', 'Banco Standard de Investimentos S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('464', 'Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('082-5', 'Banco Topázio S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M20', 'Banco Toyota do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M13', 'Banco Tricury S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('634', 'Banco Triângulo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M14', 'Banco Volkswagen S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('M23', 'Banco Volvo (Brasil) S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('655', 'Banco Votorantim S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('610', 'Banco VR S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('370', 'Banco WestLB do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('021', 'BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('719', 'Banif-Banco Internacional do Funchal (Brasil)S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('755', 'Bank of America Merrill Lynch Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('744', 'BankBoston N.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('073', 'BB Banco Popular do Brasil S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('078', 'BES Investimento do Brasil S.A.-Banco de Investimento');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('069', 'BPN Brasil Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('070', 'BRB - Banco de Brasília S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('092-2', 'Brickell S.A. Crédito, financiamento e Investimento');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('104', 'Caixa Econômica Federal');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('477', 'Citibank N.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('081-7', 'Concórdia Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('097-3', 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('085-x', 'Cooperativa Central de Crédito Urbano-CECRED');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('099-x', 'Cooperativa Central de Economia e Credito Mutuo das Unicreds');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('090-2', 'Cooperativa Central de Economia e Crédito Mutuo das Unicreds');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('089-2', 'Cooperativa de Crédito Rural da Região de Mogiana');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('087-6', 'Cooperativa Unicred Central Santa Catarina');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('098-1', 'Credicorol Cooperativa de Crédito Rural');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('487', 'Deutsche Bank S.A. - Banco Alemão');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('751', 'Dresdner Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('064', 'Goldman Sachs do Brasil Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('062', 'Hipercard Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('399', 'HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('168', 'HSBC Finance (Brasil) S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('492', 'ING Bank N.V.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('652', 'Itaú Unibanco Holding S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('341', 'Itaú Unibanco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('079', 'JBS Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('488', 'JPMorgan Chase Bank');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('014', 'Natixis Brasil S.A. Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('753', 'NBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('086-8', 'OBOE Crédito Financiamento e Investimento S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('254', 'Paraná Banco S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('409', 'UNIBANCO - União de Bancos Brasileiros S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('230', 'Unicard Banco Múltiplo S.A.');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('091-4', 'Unicred Central do Rio Grande do Sul');
INSERT INTO `bank` (`bank_code`, `name`) VALUES ('084', 'Unicred Norte do Paraná');